#!/bin/sh /etc/rc.common

# put in /etc/init.d/fan_control

START=99
STOP=80

PIDFILE=/var/run/fan_monitor_pid

start() {
    start-stop-daemon -b -S -x /usr/sbin/fan_monitor -m -p $PIDFILE
}

stop() {
    start-stop-daemon -K -p $PIDFILE
}

